repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: check-added-large-files
        args: ["--maxkb=100"]  # Optional: Ensure files aren't too large
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-executables-have-shebangs
    -   id: check-docstring-first
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-xml

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        exclude: ^dist/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [--show-traceback, --strict]

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: pylint

# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v3.2.0
#     hooks:
#     -   id: python-check-blanket-noqa
#     -   id: check-added-large-files

# -   repo: https://github.com/pre-commit/mirrors-flake8
-   repo: https://github.com/pycqa/flake8
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: flake8
        args: ["--max-line-length=88"]  # Black's default line length
