version: '3'

services:
  web:
    build: . 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  postgres:
    image: postgres:12
    container_name: rider_postgres
    environment:
      - POSTGRES_USER=rider_user
      - POSTGRES_PASSWORD=rider_password
      - POSTGRES_DBNAME=rider_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    
    # env_file:
    # - path: ./.env
    #   required: true

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  

  celery:
    build: .
    command: celery -A CORE.celery worker -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  celery_beat:
    build: .
    command:
      [
        'celery',
        '--app=CORE',
        'beat',
        '--scheduler=django_celery_beat.schedulers:DatabaseScheduler',
        '--loglevel=INFO',
      ]
    volumes:
      - ./:/app
    depends_on:
      - web
      - postgres
      - redis

volumes:
  postgres_data:  
  redis_data:  
