# Generated by Django 4.2.13 on 2024-05-23 19:53

import Driver.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RideDriver",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=Driver.models.generate_id,
                        editable=False,
                        max_length=70,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "drivers_license_picture",
                    models.URLField(blank=True, null=True),
                ),
                (
                    "drivers_license_number",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "is_drivers_licence_valid",
                    models.BooleanField(default=False),
                ),
                (
                    "home_address",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "car_number",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "car_model",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "car_color",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "car_plate_number",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("car_picture", models.URLField(blank=True, null=True)),
                (
                    "car_year",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("is_rider_car_setup", models.BooleanField(default=False)),
                ("is_driver_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
