# Generated by Django 4.2.13 on 2024-05-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Driver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridedriver",
            name="car_brand",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
