# Generated by Django 4.2.13 on 2024-05-25 16:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "AUTHENTICATION",
            "0004_remove_user_is_rider_car_setup_delete_ridercar",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="rating",
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
